version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kentaro-m/md2confl
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kentaro-m/md2confl
    steps:
      - checkout
      - run:
          name: Deploy the project
          command: |
            go get -v -t -d ./...
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            gox -output "pkg/{{.OS}}_{{.Arch}}_{{.Dir}}"
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` pkg/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
